name: daily-study

on:
  schedule:
    - cron: '15 7 * * *'
    - cron: '45 8 * * *' 
    - cron: '20 9 * * *'
    - cron: '35 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set git user
        run: |
          git config --global user.name "mingMy-00"
          git config --global user.email "wbsebqb1118@naver.com"

      - name: Create study note
        run: |
          today=$(date +'%Y-%m-%d')
          mkdir -p notes
          file_path="notes/$today.md"
          
          # 이미 오늘 파일이 있으면 종료
          if [ -f "$file_path" ]; then
            echo "Today's note already exists."
            exit 0
          fi
          
          # 다양한 내용 배열
          contents=(
            "# 개발 노트\n\n- React hooks 사용법 정리\n- useState와 useEffect 차이점 학습"
            "# 학습 기록\n\n- JavaScript 비동기 처리 방법\n- Promise와 async/await 비교"
            "# 코딩 메모\n\n- CSS Grid vs Flexbox 활용법\n- 반응형 웹 디자인 팁"
            "# 개발 일지\n\n- API 연동 방법 학습\n- REST vs GraphQL 차이점"
            "# 공부 노트\n\n- 알고리즘 문제 해결 과정\n- 시간복잡도 최적화 방법"
            "# 기술 메모\n\n- Git 브랜치 전략 학습\n- 협업 시 유용한 명령어들"
            "# 학습 정리\n\n- 데이터베이스 설계 원칙\n- 정규화와 비정규화 개념"
          )
          
          # 다양한 커밋 메시지 배열
          commit_messages=(
            "docs: 학습 내용 정리"
            "study: 새로운 개념 학습"
            "notes: 개발 관련 메모 추가"
            "docs: 기술 스택 정리"
            "update: 학습 진도 기록"
            "memo: 코딩 팁 정리"
            "docs: 개발 환경 설정 메모"
            "study: 알고리즘 문제 해결"
            "notes: 프로젝트 아이디어 기록"
            "update: 새로운 기술 학습 기록"
          )
          
          # 랜덤 선택
          content_index=$((RANDOM % ${#contents[@]}))
          message_index=$((RANDOM % ${#commit_messages[@]}))
          
          # 파일 생성
          echo -e "${contents[$content_index]}" > "$file_path"
          
          # 가끔 README도 업데이트 (20% 확률)
          if [ $((RANDOM % 5)) -eq 0 ]; then
            echo -e "# 개발 학습 노트\n\n개발 공부하면서 배운 것들을 기록하는 공간입니다.\n\n마지막 업데이트: $(date +'%Y-%m-%d')" > README.md
            git add README.md
          fi
          
          git add "$file_path"
          git commit -m "${commit_messages[$message_index]}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
