name: Daily TIL Commit
permissions:
  contents: write
on:
  schedule:
    - cron: '0 0 * * *'  # 매일 00:00 UTC = 오전 9시 KST
  workflow_dispatch:     # 수동 실행도 가능

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "mingMy-00"
          git config --global user.email "wbsebqb1118@naver.com"

      - name: Create TIL file
        run: |
          mkdir -p til
          TODAY=$(date '+%Y-%m-%d')
          echo "# TIL for $TODAY" > til/$TODAY.md
          echo "" >> til/$TODAY.md
          echo "- [ ] 오늘 공부한 내용을 여기에 정리할 예정입니다." >> til/$TODAY.md

      - name: Commit and push
        run: |
          git add .
          git commit -m "TIL: $(date '+%Y-%m-%d') 작성"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
