name: daily-til

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set git user
        run: |
          git config --global user.name "mingMy-00"
          git config --global user.email "wbsebqb1118@naver.com"

      - name: Create TIL file
        run: |
          today=$(date +'%Y-%m-%d')
          mkdir -p til
          file_path="til/$today.md"
          if [ ! -f "$file_path" ]; then
            echo "- 오늘 배운 것 정리" > "$file_path"
            git add "$file_path"
            git commit -m "TIL: $today 작성"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          else
            echo "$file_path already exists. Skipping commit."
          fi
