name: daily-til

on:
  schedule:
    - cron: '56 5 * * *'  # 매일 오후 2시 56분 (KST)
  workflow_dispatch:

permissions:
  contents: write  # ← 추가 필요!

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set git user
        run: |
          git config --global user.name "mingMy-00"
          git config --global user.email "wbsebqb1118@naver.com"

      - name: Create TIL file
        run: |
          today=$(date +'%Y-%m-%d')
          mkdir -p til
          echo "- 오늘 배운 것 정리" > til/$today.md
          git add .
          git commit -m "TIL: $today 작성"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
